name: Release Button app

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # Checkout repository
      - name: Checkout repository
        uses: actions/checkout@v3
  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Checkout respository
        uses: actions/checkout@v3
    
      # Login to Docker
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      
      # Build and push to Docker Hub
      - name: Build and push
        uses: docker/build-push-action@v4
        with:
          push: true
          tags: victoriousglorious/button:latest
      
      # Deployt to Fly.io
      - name: Deploy to Fly.io
        uses: superfly/flyctl-actions@v1
        with:
          args: deploy
        env: 
          FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
      
